import type { Metadata } from "next";
import "./globals.css";
import { ConvexClientProvider } from "./convex-client-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* this children make sure that anythinf that we wrap in this component will rendered within in*/}
      <body><ConvexClientProvider>{children}</ConvexClientProvider></body>
    </html>
  );
}
